// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olhsqptalpvzczshnglu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9saHNxcHRhbHB2emN6c2huZ2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjM5NTksImV4cCI6MjA2NTAzOTk1OX0.oQcSNi5ILiLMOPz6xCOYzjODB_LgdWIc1ac9s7iLd4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);